import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ClerkProvider, SignInButton, SignedIn, SignedOut, UserButton } from '@clerk/nextjs'
import { dark } from '@clerk/themes';
import React from 'react';
import ThemeChange from '@/themeChange';


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const Theme = () => {
    if(typeof window !== "undefined"){
      return document.getElementById("html-root")?.classList.value
    }
  }
  return (
    <ClerkProvider>
      <html lang="ja" id='html-root'>
        <body className={inter.className}>
          <header className='flex justify-between	p-5'>
            <h1 className='text-2xl'>Test Application</h1>
            <ThemeChange />
            <SignedIn>
              <UserButton />
            </SignedIn>
            <SignedOut>
              <SignInButton mode='modal' />
            </SignedOut>
          </header>
          {children}
          </body>
      </html>
    </ClerkProvider>
  )
}
